In [68]:
import numpy as np

In [69]:
#inputs
inp = []
#1
inp.append([
    [-1,-1,1,-1,-1],
    [-1,1,1,-1,-1],
    [-1,-1,1,-1,-1],
    [-1,-1,1,-1,-1],
    [-1,-1,1,-1,-1],
    [-1,-1,1,-1,-1],
    [-1,1,1,1,-1]
])
#2
inp.append([
    [-1,1,1,1,-1],
    [1,-1,-1,-1,1],
    [-1,-1,-1,-1,1],
    [-1,-1,-1,1,-1],
    [-1,-1,1,-1,-1],
    [-1,1,-1,-1,-1],
    [1,1,1,1,1]
])

#3
inp.append([
    [-1,1,1,1,-1],
    [1,-1,-1,-1,1],
    [-1,-1,-1,-1,1],
    [-1,-1,1,1,-1],
    [-1,-1,-1,-1,1],
    [1,-1,-1,-1,1],
    [-1,1,1,1,-1]
])

#4
inp.append([
    [-1,-1,-1,-1,1],
    [1,-1,-1,1,1],
    [-1,-1,1,-1,1],
    [-1,1,-1,-1,1],
    [1,1,1,1,1],
    [-1,-1,-1,-1,1],
    [-1,-1,-1,-1,1]
])

#5
inp.append([
    [1,1,1,1,1],
    [1,-1,-1,-1,-1],
    [1,-1,-1,-1,-1],
    [1,1,1,1,-1],
    [-1,-1,-1,-1,1],
    [-1,-1,-1,-1,1],
    [1,1,1,1,-1]
])

#6
inp.append([
    [-1,1,1,1,1],
    [1,-1,-1,-1,-1],
    [1,-1,-1,-1,-1],
    [1,1,1,1,-1],
    [1,-1,-1,-1,1],
    [1,-1,-1,-1,1],
    [-1,1,1,1,-1]
])

#7
inp.append([
    [1,1,1,1,1],
    [-1,-1,-1,-1,1],
    [-1,-1,-1,1,-1],
    [-1,-1,-1,1,-1],
    [-1,-1,1,-1,-1],
    [-1,-1,1,-1,-1],
    [-1,1,-1,-1,-1]
])

#8
inp.append([
    [-1,1,1,1,-1],
    [1,-1,-1,-1,1],
    [1,-1,-1,-1,1],
    [-1,1,1, 1, -1],
    [1,-1,-1,-1,1],
    [1,-1,-1,-1,1],
    [-1,1,1, 1, -1]
])

#9
inp.append([
    [-1,1,1,1,-1],
    [1,-1,-1,-1,1],
    [1,-1,-1,-1,1],
    [-1,1,1, 1, 1],
    [-1,-1,-1,-1,1],
    [-1,-1,-1,-1,1],
    [1,1,1, 1, -1]
])

#0
inp.append([
    [-1,1,1,1,-1],
    [1,-1,-1,-1,1],
    [1,-1,-1,-1,1],
    [1,-1,-1,-1,1],
    [1,-1,-1,-1,1],
    [1,-1,-1,-1,1],
    [-1,1,1,1,-1]
])


In [70]:
#training
weight = []
for i in inp:
    weight.append(np.dot(np.transpose(i),i))
    
print(weight)

[array([[ 7,  3, -7,  5,  7],
       [ 3,  7, -3,  5,  3],
       [-7, -3,  7, -5, -7],
       [ 5,  5, -5,  7,  5],
       [ 7,  3, -7,  5,  7]]), array([[ 7,  1,  1,  1,  5],
       [ 1,  7,  3,  3, -1],
       [ 1,  3,  7,  3, -1],
       [ 1,  3,  3,  7, -1],
       [ 5, -1, -1, -1,  7]]), array([[ 7, -1, -3, -3,  3],
       [-1,  7,  5,  5, -5],
       [-3,  5,  7,  7, -7],
       [-3,  5,  7,  7, -7],
       [ 3, -5, -7, -7,  7]]), array([[ 7,  3,  3,  7, -3],
       [ 3,  7,  3,  3, -3],
       [ 3,  3,  7,  3, -3],
       [ 7,  3,  3,  7, -3],
       [-3, -3, -3, -3,  7]]), array([[ 7,  3,  3,  3, -5],
       [ 3,  7,  7,  7, -1],
       [ 3,  7,  7,  7, -1],
       [ 3,  7,  7,  7, -1],
       [-5, -1, -1, -1,  7]]), array([[ 7, -5, -5, -5, -1],
       [-5,  7,  7,  7, -1],
       [-5,  7,  7,  7, -1],
       [-5,  7,  7,  7, -1],
       [-1, -1, -1, -1,  7]]), array([[ 7,  5,  3,  3,  5],
       [ 5,  7,  1,  1,  3],
       [ 3,  1,  7, -1,  1],
       [ 3,  1, -1,  7,  1],
 

In [71]:
weights = np.sum(weight,0)
print(weights)

[[ 70  -6 -20  -4  24]
 [ -6  70  44  52 -24]
 [-20  44  70  42 -38]
 [ -4  52  42  70 -26]
 [ 24 -24 -38 -26  70]]


In [72]:
step_function = lambda x : 1 if x>0 else -1   

In [73]:
def apply(arr):
    for i in range(len(arr)):
        for j in range(arr.shape[-1]):
            arr[i][j] = step_function(arr[i][j])
    return arr

In [74]:
#Testing
test_out = []
for i in inp:
    test_out.append(apply(np.dot(i,weights)))

print(test_out)
    

[array([[-1, -1,  1, -1, -1],
       [-1,  1,  1,  1, -1],
       [-1, -1,  1, -1, -1],
       [-1, -1,  1, -1, -1],
       [-1, -1,  1, -1, -1],
       [-1, -1,  1, -1, -1],
       [-1,  1,  1,  1, -1]]), array([[-1,  1,  1,  1, -1],
       [ 1, -1, -1, -1,  1],
       [-1, -1, -1, -1,  1],
       [-1, -1, -1,  1, -1],
       [-1, -1,  1, -1, -1],
       [-1,  1, -1, -1, -1],
       [ 1,  1,  1,  1,  1]]), array([[-1,  1,  1,  1, -1],
       [ 1, -1, -1, -1,  1],
       [-1, -1, -1, -1,  1],
       [-1,  1,  1,  1, -1],
       [-1, -1, -1, -1,  1],
       [ 1, -1, -1, -1,  1],
       [-1,  1,  1,  1, -1]]), array([[-1, -1, -1, -1,  1],
       [ 1, -1, -1, -1,  1],
       [-1, -1, -1, -1,  1],
       [-1, -1, -1, -1,  1],
       [ 1,  1,  1,  1,  1],
       [-1, -1, -1, -1,  1],
       [-1, -1, -1, -1,  1]]), array([[ 1,  1,  1,  1,  1],
       [ 1, -1, -1, -1,  1],
       [ 1, -1, -1, -1,  1],
       [ 1,  1,  1,  1, -1],
       [-1, -1, -1, -1,  1],
       [-1, -1, -1, -1,  1],
     

In [81]:
def pattern(arr):
    for i in arr:
        print()
        for j in range(len(i)):
            print()
            for k in range(i.shape[1]):
                if(i[j][k] == 1):
                    print('#',end=" ")
                else:
                    print('.',end=" ")

In [76]:
pattern(test_out)



. . # . . 
. # # # . 
. . # . . 
. . # . . 
. . # . . 
. . # . . 
. # # # . 

. # # # . 
# . . . # 
. . . . # 
. . . # . 
. . # . . 
. # . . . 
# # # # # 

. # # # . 
# . . . # 
. . . . # 
. # # # . 
. . . . # 
# . . . # 
. # # # . 

. . . . # 
# . . . # 
. . . . # 
. . . . # 
# # # # # 
. . . . # 
. . . . # 

# # # # # 
# . . . # 
# . . . # 
# # # # . 
. . . . # 
. . . . # 
# # # # . 

. # # # . 
# . . . # 
# . . . # 
# # # # . 
# . . . # 
# . . . # 
. # # # . 

# # # # # 
. . . . # 
. . . # . 
. . . # . 
. . # . . 
. . # . . 
. # . . . 

. # # # . 
# . . . # 
# . . . # 
. # # # . 
# . . . # 
# . . . # 
. # # # . 

. # # # . 
# . . . # 
# . . . # 
. # # # . 
. . . . # 
. . . . # 
# # # # . 

. # # # . 
# . . . # 
# . . . # 
# . . . # 
# . . . # 
# . . . # 
. # # # . 

In [83]:
#6 with missing values
val = []
val.append([
    [-1,1,1,0,1],
    [1,0,-1,-1,-1],
    [1,-1,-1,0,-1],
    [1,1,1,1,-1],
    [1,0,-1,-1,1],
    [1,-1,-1,-1,1],
    [-1,1,1,0,-1]
])
val = np.array(val)
result = []
result.append(apply(np.dot(val[0],weights)))
pattern(result)



. # # # . 
# . . . # 
# . . . # 
# # # # . 
# . . . # 
# . . . # 
. # # # . 

In [84]:
#batch iterative
itr = []
for i in test_out:
    itr.append(apply(np.dot(i,weights)))
pattern(itr)



. . # . . 
. # # # . 
. . # . . 
. . # . . 
. . # . . 
. . # . . 
. # # # . 

. # # # . 
# . . . # 
. . . . # 
. . . # . 
. . # . . 
. # . . . 
# # # # # 

. # # # . 
# . . . # 
. . . . # 
. # # # . 
. . . . # 
# . . . # 
. # # # . 

. . . . # 
# . . . # 
. . . . # 
. . . . # 
# # # # # 
. . . . # 
. . . . # 

# # # # # 
# . . . # 
# . . . # 
# # # # . 
. . . . # 
. . . . # 
# # # # . 

. # # # . 
# . . . # 
# . . . # 
# # # # . 
# . . . # 
# . . . # 
. # # # . 

# # # # # 
. . . . # 
. . . # . 
. . . # . 
. . # . . 
. . # . . 
. # . . . 

. # # # . 
# . . . # 
# . . . # 
. # # # . 
# . . . # 
# . . . # 
. # # # . 

. # # # . 
# . . . # 
# . . . # 
. # # # . 
. . . . # 
. . . . # 
# # # # . 

. # # # . 
# . . . # 
# . . . # 
# . . . # 
# . . . # 
# . . . # 
. # # # . 

There were no improvements on iterative autoassosiative net, it is the same as autoassosiative.