In [12]:
import numpy as np

In [13]:
#input
A = np.array([[-1,-1,-1,1,-1,-1,-1],
              [-1,-1,-1,1,-1,-1,-1],
              [-1,-1,1,-1,1,-1,-1],
              [-1,-1,1,-1,1,-1,-1],
              [-1,-1,1,1,1,-1,-1],
              [-1,1,-1,-1,-1,1,-1],
              [-1,1,-1,-1,-1,1,-1],
              [1,-1,-1,-1,-1,-1,1],
              [1,-1,-1,-1,-1,-1,1]])

B = np.array([[1,1,1,1,1,-1,-1],
              [1,-1,-1,-1,-1,1,-1],
              [1,-1,-1,-1,-1,-1,1],
              [1,-1,-1,-1,-1,1,-1],
              [1,1,1,1,1,-1,-1],
              [1,-1,-1,-1,-1,1,-1],
              [1,-1,-1,-1,-1,-1,1],
              [1,-1,-1,-1,-1,1,-1],
              [1,1,1,1,1,-1,-1]])

C = np.array([[-1,-1,1,1,1,-1,-1],
              [-1,1,-1,-1,-1,1,-1],
              [1,-1,-1,-1,-1,-1,1],
              [1,-1,-1,-1,-1,-1,-1],
              [1,-1,-1,-1,-1,-1,-1],
              [1,-1,-1,-1,-1,-1,-1],
              [1,-1,-1,-1,-1,-1,1],
              [-1,1,-1,-1,-1,1,-1],
              [-1,-1,1,1,1,-1,-1]])

In [14]:
inp = []
arr =[A,B,C]
for i in arr:
    inp.append(np.ravel(i))
inp = np.array(inp)
inp

array([[-1, -1, -1,  1, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1, -1, -1,
         1, -1,  1, -1, -1, -1, -1,  1, -1,  1, -1, -1, -1, -1,  1,  1,
         1, -1, -1, -1,  1, -1, -1, -1,  1, -1, -1,  1, -1, -1, -1,  1,
        -1,  1, -1, -1, -1, -1, -1,  1,  1, -1, -1, -1, -1, -1,  1],
       [ 1,  1,  1,  1,  1, -1, -1,  1, -1, -1, -1, -1,  1, -1,  1, -1,
        -1, -1, -1, -1,  1,  1, -1, -1, -1, -1,  1, -1,  1,  1,  1,  1,
         1, -1, -1,  1, -1, -1, -1, -1,  1, -1,  1, -1, -1, -1, -1, -1,
         1,  1, -1, -1, -1, -1,  1, -1,  1,  1,  1,  1,  1, -1, -1],
       [-1, -1,  1,  1,  1, -1, -1, -1,  1, -1, -1, -1,  1, -1,  1, -1,
        -1, -1, -1, -1,  1,  1, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1,
        -1, -1, -1,  1, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1, -1, -1,
         1, -1,  1, -1, -1, -1,  1, -1, -1, -1,  1,  1,  1, -1, -1]])

In [15]:
#target
a = np.array([[-1,1,-1],
              [1,-1,1],
              [1,1,1],
              [1,-1,1],
              [1,-1,1]])

b = np.array([[1,1,-1],
              [1,-1,1],
              [1,1,-1],
              [1,-1,1],
              [1,1,-1]])

c = np.array([[1,1,1],
              [1,-1,-1],
              [1,-1,-1],
              [1,-1,-1],
              [1,1,1]])

In [16]:
target = []
arr =[a,b,c]
for i in arr:
    target.append(np.ravel(i))
target = np.array(target)
target

array([[-1,  1, -1,  1, -1,  1,  1,  1,  1,  1, -1,  1,  1, -1,  1],
       [ 1,  1, -1,  1, -1,  1,  1,  1, -1,  1, -1,  1,  1,  1, -1],
       [ 1,  1,  1,  1, -1, -1,  1, -1, -1,  1, -1, -1,  1,  1,  1]])

In [20]:
#training
weight = []
for i,j in zip(inp,target):
    i = np.matrix(i)
    j = np.matrix(j)
    weight.append(np.dot(np.transpose(i),j))
    
print(weight)

[matrix([[ 1, -1,  1, -1,  1, -1, -1, -1, -1, -1,  1, -1, -1,  1, -1],
        [ 1, -1,  1, -1,  1, -1, -1, -1, -1, -1,  1, -1, -1,  1, -1],
        [ 1, -1,  1, -1,  1, -1, -1, -1, -1, -1,  1, -1, -1,  1, -1],
        [-1,  1, -1,  1, -1,  1,  1,  1,  1,  1, -1,  1,  1, -1,  1],
        [ 1, -1,  1, -1,  1, -1, -1, -1, -1, -1,  1, -1, -1,  1, -1],
        [ 1, -1,  1, -1,  1, -1, -1, -1, -1, -1,  1, -1, -1,  1, -1],
        [ 1, -1,  1, -1,  1, -1, -1, -1, -1, -1,  1, -1, -1,  1, -1],
        [ 1, -1,  1, -1,  1, -1, -1, -1, -1, -1,  1, -1, -1,  1, -1],
        [ 1, -1,  1, -1,  1, -1, -1, -1, -1, -1,  1, -1, -1,  1, -1],
        [ 1, -1,  1, -1,  1, -1, -1, -1, -1, -1,  1, -1, -1,  1, -1],
        [-1,  1, -1,  1, -1,  1,  1,  1,  1,  1, -1,  1,  1, -1,  1],
        [ 1, -1,  1, -1,  1, -1, -1, -1, -1, -1,  1, -1, -1,  1, -1],
        [ 1, -1,  1, -1,  1, -1, -1, -1, -1, -1,  1, -1, -1,  1, -1],
        [ 1, -1,  1, -1,  1, -1, -1, -1, -1, -1,  1, -1, -1,  1, -1],
        [ 1, -1,  1

In [22]:
#adding weight
weights = np.sum(weight,0)
print(weights)

[[ 1 -1 -1 -1  1  1 -1  1 -1 -1  1  1 -1  1 -3]
 [ 1 -1 -1 -1  1  1 -1  1 -1 -1  1  1 -1  1 -3]
 [ 3  1  1  1 -1 -1  1 -1 -3  1 -1 -1  1  3 -1]
 [ 1  3 -1  3 -3  1  3  1 -1  3 -3  1  3  1  1]
 [ 3  1  1  1 -1 -1  1 -1 -3  1 -1 -1  1  3 -1]
 [-1 -3  1 -3  3 -1 -3 -1  1 -3  3 -1 -3 -1 -1]
 [-1 -3  1 -3  3 -1 -3 -1  1 -3  3 -1 -3 -1 -1]
 [ 1 -1 -1 -1  1  1 -1  1 -1 -1  1  1 -1  1 -3]
 [ 1 -1  3 -1  1 -3 -1 -3 -1 -1  1 -3 -1  1  1]
 [-1 -3  1 -3  3 -1 -3 -1  1 -3  3 -1 -3 -1 -1]
 [-3 -1 -1 -1  1  1 -1  1  3 -1  1  1 -1 -3  1]
 [-1 -3  1 -3  3 -1 -3 -1  1 -3  3 -1 -3 -1 -1]
 [ 3  1  1  1 -1 -1  1 -1 -3  1 -1 -1  1  3 -1]
 [-1 -3  1 -3  3 -1 -3 -1  1 -3  3 -1 -3 -1 -1]
 [ 3  1  1  1 -1 -1  1 -1 -3  1 -1 -1  1  3 -1]
 [-1 -3  1 -3  3 -1 -3 -1  1 -3  3 -1 -3 -1 -1]
 [-3 -1 -1 -1  1  1 -1  1  3 -1  1  1 -1 -3  1]
 [-1 -3  1 -3  3 -1 -3 -1  1 -3  3 -1 -3 -1 -1]
 [-3 -1 -1 -1  1  1 -1  1  3 -1  1  1 -1 -3  1]
 [-1 -3  1 -3  3 -1 -3 -1  1 -3  3 -1 -3 -1 -1]
 [ 3  1  1  1 -1 -1  1 -1 -3  1 -1 -1  1

In [41]:
#testing
out = []
for i in inp:
    i = np.matrix(i)
    out.append(np.where(np.dot(i,weights)>0,1,-1))
out

[array([[-1,  1, -1,  1, -1,  1,  1,  1,  1,  1, -1,  1,  1, -1,  1]]),
 array([[ 1,  1, -1,  1, -1,  1,  1,  1, -1,  1, -1,  1,  1,  1, -1]]),
 array([[ 1,  1,  1,  1, -1, -1,  1, -1, -1,  1, -1, -1,  1,  1,  1]])]

In [51]:
def pattern(arr):
    for i in arr:
        print()
        for j in range(len(i)):
            print()
            for k in range(i.shape[1]):
                if(i[j][k] == 1):
                    print('#',end=" ")
                else:
                    print('.',end=" ")

In [52]:
out = np.array(out)
pattern(out.reshape(3,5,3))



. # . 
# . # 
# # # 
# . # 
# . # 

# # . 
# . # 
# # . 
# . # 
# # . 

# # # 
# . . 
# . . 
# . . 
# # # 

In [53]:
#noisy input
B = np.array([[1,1,1,1,1,-1,-1],
              [1,-1,-1,-1,-1,0,-1],
              [1,-1,1,-1,-1,-1,1],
              [1,-1,-1,-1,-1,1,-1],
              [1,1,0,1,1,-1,-1],
              [1,-1,-1,-1,0,1,-1],
              [1,-1,-1,-1,-1,-1,1],
              [1,1,-1,-1,-1,1,-1],
              [1,1,1,1,1,-1,0]])

B = np.ravel(B)
B = np.matrix(B)
np.where(np.dot(B,weights)>0,1,-1)


array([[ 1,  1, -1,  1, -1,  1,  1,  1, -1,  1, -1,  1,  1,  1, -1]])

In [54]:
pattern(np.where(np.dot(B,weights)>0,1,-1).reshape(1,5,3))



# # . 
# . # 
# # . 
# . # 
# # . 

#Even for missing values hetroassosiative classifies it correctly

In [ ]:
E = np.array([[1,1,1,1,1,1,1],
              [1,-1,-1,-1,-1,-1,-1],
              [1,-1,-1,-1,-1,-1,-1],
              [1,-1,-1,-1,-1,-1,-1],
              [1,-1,-1,-1,-1,-1,-1],
              [1,-1,-1,-1,-1,-1,-1],
              [1,-1,-1,-1,-1,-1,-1],
              [1,-1,-1,-1,-1,-1,-1],
              [1,1,1,1,1,1,1]])